# Generated by Django 4.2.8 on 2024-05-20 12:26

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_project_cover_alter_projectgallery_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[None, 600], upload_to='services/projects/'),
        ),
        migrations.AlterField(
            model_name='projectgallery',
            name='img',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[None, 400], upload_to='services/projects/'),
        ),
    ]
