# Generated by Django 4.2.8 on 2024-03-30 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_contactus_email_contactus_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='services',
            new_name='service',
        ),
    ]
