# Generated by Django 4.2.8 on 2024-03-26 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationlevel',
            name='education_stage',
        ),
        migrations.AddField(
            model_name='educationlevel',
            name='educationـgrade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educationـgrade', to='education.educationstage'),
        ),
    ]
