# Generated by Django 4.2.8 on 2024-03-26 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_educationlevel_educationـgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationlevel',
            name='educationـgrade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_levels', to='education.educationstage'),
        ),
    ]
