# Generated by Django 4.2.8 on 2024-03-30 14:45

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_educationstage_image_alter_education_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[500, 300], upload_to='stage/'),
        ),
        migrations.AlterField(
            model_name='educationstage',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[500, 500], upload_to='educationـstage/'),
        ),
    ]
